### ISSUE TITLE
Tuple not list

### ISSUE THREAD

**Issue by Martusia11** [hbldh/wlmetrics#1]
Hello,
I am writing a class for quaternions. I would like to give the quaternion coordinates as a tuple, not as a list. How can I do this?

Here is my code:
```python
class Quaternion(object):

    def __init__(self, elements):
        if len(elements) != 4:
            raise ValueError("Quaternion init vector must be of length 4.")
        self.elements = elements
```
What to do to write elements as a tuple not as list. When I try to run my program in Jupyter everything is good, but I must type Quaternion([1,2,3,4]) - so it is not a tuple, but list.

**Comment by hbldh** [comment]
Late reply, sorry. Not sure if it it is needed any more, but here goes.

You should just be able to create object as `Quaternion((1,2,3,4))`. Your code works with tuples as well.
